services:
  # Cleanuparr - Arr Stack Cleanup Tool
  cleanuparr:
    image: ghcr.io/cleanuparr/cleanuparr:latest
    container_name: cleanuparr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["all", "apps"]
    networks:
      - default
    ports:
      - "$CLEANUPARR_PORT:11011"
    volumes:
      - $DOCKERDIR/appdata/cleanuparr:/config
    environment:
      TZ: $TZ
      PORT: 11011
      PUID: $PUID
      PGID: $PGID
      UMASK: 022
    stop_signal: SIGTERM
    stop_grace_period: 30s
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11011/health"]
      interval: 30s
      timeout: 10s
      start_period: 30s
      retries: 3
    # DOCKER-LABELS-PLACEHOLDER
