services:
  # Geek Army Support 
  support:
    image: tailscale/tailscale:stable
    container_name: support
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["core", "all"]
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun
    environment:
      - TS_AUTH_KEY=$TS_AUTH_KEY
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_ACCEPT_DNS=false
    # DOCKER-LABELS-PLACEHOLDER
