services:
  # Watchtower - Container Monitoring and Management
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    security_opt:
      - no-new-privileges:true
    restart: always
    profiles: ["all", "aps"]
    networks:
      - default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: $TZ
      WATCHTOWER_CLEANUP: true                                        
      WATCHTOWER_INCLUDE_RESTARTING: true
      WATCHTOWER_POLL_INTERVAL: 36000                  
      # WATCHTOWER_SCHEDULE: 0 0 9 * * *
      # WATCHTOWER_DEBUG: true   
      # WATCHTOWER_LABEL_ENABLE: true
    # DOCKER-LABELS-PLACEHOLDER